apiVersion: 1

datasources:
  - name: Games Assistant PostgreSQL
    uid: games-assistant-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: games_assistant
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: games_assistant
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: false